name: github action demo
on: [push]

jobs:
  demo-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "${{ github.ref }}"

      - name: install dependency
      - run: yarn lint
    
