name: github action demo
on: [push]

jobs:
  demo-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repo
        uses: actions/checkout@v3

      - name: Echo test
        run: echo "${{ github.ref }}"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: install dependency
        run: yarn

      - name: lint
        run: yarn lint
    
