name: github action demo
on: [push]

jobs:
  demo-push:
    runs-on: ubuntu-latest
    # steps:
    #   - runs: echo "${{ github.ref }}"

    steps:
      - name: install dependency
      - uses: actions/checkout@v3
    
    steps:
      - run: yarn lint

